apiVersion: v1
kind: Secret
metadata:
  name: feishu-secrets
  namespace: feishu-suite
type: Opaque
stringData:
  FEISHU_APP_ID: "cli_aa836c620e38dbb4"
  FEISHU_APP_SECRET: "ZrFIJ2k911lRNllVsdbo0gMCxbJx3Mge"
  MYSQL_ROOT_PASSWORD: "admin"
  MYSQL_PASSWORD: "password"
  REDIS_PASSWORD: ""
  ADMIN_USER: "admin"
  ADMIN_PASSWORD: "admin123"